{{ if .Values.controllerManager.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "workspace-operator.serviceAccountName" . }}
  labels:
  {{- include "workspace-operator.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}
{{- end }}