apiVersion: core.telespazio-uk.io/v1alpha1
kind: Workspace
metadata:
  labels:
    app.kubernetes.io/name: workspace-operator
    app.kubernetes.io/managed-by: kustomize
  name: test
spec:
  username: test
  namespace: ws-test
  storage:
    pvcName: pvc-test
    storageClass: file-storage
    size: 1Gi
    awsEFS:
      rootDirectory: /workspaces/test
