apiVersion: core.telespazio-uk.io/v1alpha1
kind: Workspace
metadata:
  labels:
    app.kubernetes.io/name: workspace-operator
    app.kubernetes.io/managed-by: kustomize
  name: workspace-sample
spec:
  storage:
    storageClass: file-storage
    size: 2.5Gi
